### ISSUE TITLE
Rebuild all?

### ISSUE THREAD

**Issue by risc26z** [DoDoENT/neovim-additional-tasks#1]
This is a really nice plugin.  :-) Is it possible to add a 'rebuild' task (clean, then build all)? I find that's a very common task when chasing warnings.

**Comment by DoDoENT** [comment]
Sure! It should be simple.

You can even do it yourself:

Simply add a new entry below [this line](https://github.com/DoDoENT/neovim-additional-tasks/blob/master/lua/tasks/module/cmake_kits.lua#L430) with the content:

```lua
rebuild_all = { clean, build_all },
```

Also, feel free to make a PR if this change works well for you.

**Comment by DoDoENT** [comment]
Implemented in [d8f0ae70514a6fdb07b48b10c18aaaf65bdfbfbf](https://github.com/DoDoENT/neovim-additional-tasks/commit/d8f0ae70514a6fdb07b48b10c18aaaf65bdfbfbf).
